### ISSUE TITLE
JSX syntax in the library

### ISSUE THREAD

**Issue by scabbiaza** [react-component/css-transition-group#1]
Hello, I try to use your lib but get error by compilation:

`Error: Parsing file node_modules/rc-css-transition-group/lib/CSSTransitionGroup.js: Unexpected token (144:11)
`

How to use build files by import? without JSX syntax?

**Comment by yiminghe** [comment]
use webpack to build your project:

https://github.com/yiminghe/learning-react/blob/master/webpack.common.config.js#L30

**Comment by scabbiaza** [comment]
Thank you for the answer.
We just were about to use webpack and moved to it from gulp some days ago :)

There was an issue with browserify, that create second copy of react by using react.addons, that is why we wanted to use your lib.

Now when we don't have this issue anymore, I think we can use react.addons.

I still think it's better to include compiled files when it goes about library, because build process works much quicker in this case.

Again, thank you!

**Comment by yiminghe** [comment]
Glad to be helpful for you.

For me, I am not comfortable to require 'react/addons' in source files, I just make react external and load react.js in head.
